### ISSUE TITLE
Running example.py throws a NameError

### ISSUE THREAD

**Issue by mooneyse** [achael/eht-imaging#13]
I tried running example.py line by line in a Python terminal but it fails. It throws an error specifically on line 76 of `example.py`:

`out  = eh.imager_func(obs, gaussprior, gaussprior, flux, d1 = 'bs', s1 = 'simple', alpha_s1 = 1, alpha_d1 = 100, alpha_flux = 100, alpha_cm = 50, maxit = 100)`

Here's the traceback:

```
Getting bispectra: type: vis count: min scan 107/107 Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sean/eht/eht-imaging/ehtim/imaging/imager_utils.py", line 178, in imager_func
    (data1, sigma1, A1) = chisqdata(Obsdata, Prior, embed_mask, d1, **kwargs)#ttype=ttype, fft_pad_factor=fft_pad_factor, conv_func=grid_conv, p_rad=grid_prad, order=fft_interp, debias=debias,snrcut=snrcut)
  File "/home/sean/eht/eht-imaging/ehtim/imaging/imager_utils.py", line 583, in chisqdata
    (data, sigma, A) = chisqdata_bs(Obsdata, Prior, mask, **kwargs)
  File "/home/sean/eht/eht-imaging/ehtim/imaging/imager_utils.py", line 1884, in chisqdata_bs
    snrmask = np.abs(biarr['bispec']/data_arr['sigmab']) > snrcut
NameError: name 'data_arr' is not defined
```

Where should I define the global name `data_arr` for it to work?

**Comment by klbouman** [comment]
We apologize for this error. This was a bug due to a recent variable name change. It should be fixed now.

**Comment by mooneyse** [comment]
Excellent, thank you.
